#!/usr/bin/env python3
"""
Populate Material Contaminants (Hybrid Approach)

Syncs contamination data from Contaminants.yaml to Materials.yaml
as a CACHED field for fast lookups. Contaminants.yaml remains the
single source of truth.

This enables O(1) lookups in BOTH directions:
- "What contaminants affect Aluminum?" → O(1) cached lookup
- "What materials can have rust?" → O(1) direct lookup

Usage:
    # Populate all materials
    python3 scripts/sync/populate_material_contaminants.py
    
    # Dry run (preview changes)
    python3 scripts/sync/populate_material_contaminants.py --dry-run
    
    # Specific materials only
    python3 scripts/sync/populate_material_contaminants.py --materials Aluminum Steel Copper
    
    # Verbose output
    python3 scripts/sync/populate_material_contaminants.py --verbose

Architecture:
    - Contaminants.yaml: SOURCE OF TRUTH (edit this)
    - Materials.yaml: CACHED DATA (generated by this script)
    - Run this script after any Contaminants.yaml changes

Author: AI Assistant
Date: November 26, 2025
"""

import argparse
import sys
from pathlib import Path
from typing import Dict, List
from collections import defaultdict

# Use shared YAML utilities
from shared.utils.file_io import read_yaml_file, write_yaml_file

# Add project root to path
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))


def build_material_contaminant_index(contaminants_data: Dict) -> Dict[str, Dict[str, List[str]]]:
    """
    Build reverse index from contamination patterns to materials.
    
    Returns:
        {
            'Material Name': {
                'valid': ['pattern-id-1', 'pattern-id-2'],
                'prohibited': ['pattern-id-3']
            }
        }
    """
    patterns = contaminants_data.get('contamination_patterns', {})
    material_index = defaultdict(lambda: {'valid': [], 'prohibited': []})
    
    for pattern_id, pattern_data in patterns.items():
        # Valid materials (can have this contamination)
        for material in pattern_data.get('valid_materials', []):
            material_index[material]['valid'].append(pattern_id)
        
        # Prohibited materials (cannot have this contamination)
        for material in pattern_data.get('prohibited_materials', []):
            material_index[material]['prohibited'].append(pattern_id)
    
    return dict(material_index)


def populate_materials(
    materials_data: Dict,
    contaminant_index: Dict[str, Dict[str, List[str]]],
    specific_materials: List[str] = None,
    verbose: bool = False
) -> Dict:
    """
    Populate common_contaminants field in Materials.yaml.
    
    Args:
        materials_data: Materials.yaml data
        contaminant_index: Material → Contaminants mapping
        specific_materials: Only update these materials (None = all)
        verbose: Print detailed progress
    
    Returns:
        Updated materials_data with common_contaminants populated
    """
    materials = materials_data.get('materials', {})
    
    updated_count = 0
    skipped_count = 0
    added_count = 0
    
    for material_name, material_data in materials.items():
        # Filter by specific materials if requested
        if specific_materials and material_name not in specific_materials:
            continue
        
        # Get contamination data for this material
        contaminants = contaminant_index.get(material_name, {})
        valid_contaminants = contaminants.get('valid', [])
        prohibited_contaminants = contaminants.get('prohibited', [])
        
        # Check if material has any contamination data
        if not valid_contaminants and not prohibited_contaminants:
            if verbose:
                print(f"   ⏭️  {material_name}: No contamination data")
            skipped_count += 1
            continue
        
        # Update material data
        old_valid = material_data.get('common_contaminants', [])
        old_prohibited = material_data.get('prohibited_contaminants', [])
        
        # Sort for consistent ordering
        valid_contaminants.sort()
        prohibited_contaminants.sort()
        
        # Update fields
        material_data['common_contaminants'] = valid_contaminants
        if prohibited_contaminants:
            material_data['prohibited_contaminants'] = prohibited_contaminants
        
        # Track changes
        if old_valid != valid_contaminants or old_prohibited != prohibited_contaminants:
            updated_count += 1
            added_count += len(valid_contaminants)
            
            if verbose:
                print(f"   ✅ {material_name}:")
                print(f"      Valid: {len(valid_contaminants)} contaminants")
                if prohibited_contaminants:
                    print(f"      Prohibited: {len(prohibited_contaminants)} contaminants")
                
                # Show what changed
                added_valid = set(valid_contaminants) - set(old_valid)
                removed_valid = set(old_valid) - set(valid_contaminants)
                
                if added_valid:
                    print(f"      Added: {', '.join(sorted(added_valid)[:3])}" + 
                          (f" (+{len(added_valid)-3} more)" if len(added_valid) > 3 else ""))
                if removed_valid:
                    print(f"      Removed: {', '.join(sorted(removed_valid)[:3])}" +
                          (f" (+{len(removed_valid)-3} more)" if len(removed_valid) > 3 else ""))
    
    return materials_data, updated_count, skipped_count, added_count


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description='Populate material contaminants from Contaminants.yaml',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Populate all materials
  populate_material_contaminants.py
  
  # Dry run (preview changes)
  populate_material_contaminants.py --dry-run
  
  # Specific materials only
  populate_material_contaminants.py --materials Aluminum Steel Copper
  
  # Verbose output
  populate_material_contaminants.py --verbose

Architecture:
  Contaminants.yaml = SOURCE OF TRUTH (edit this manually)
  Materials.yaml = CACHED DATA (generated by this script)
  
  After editing Contaminants.yaml, run this script to sync cache.
"""
    )
    
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Preview changes without modifying Materials.yaml'
    )
    
    parser.add_argument(
        '--materials',
        nargs='+',
        help='Only update these specific materials'
    )
    
    parser.add_argument(
        '--verbose', '-v',
        action='store_true',
        help='Print detailed progress'
    )
    
    parser.add_argument(
        '--no-backup',
        action='store_true',
        help='Skip creating backup file'
    )
    
    args = parser.parse_args()
    
    # File paths
    contaminants_file = project_root / 'data' / 'contaminants' / 'Contaminants.yaml'
    materials_file = project_root / 'data' / 'materials' / 'Materials.yaml'
    
    # Validate files exist
    if not contaminants_file.exists():
        print(f"❌ Error: {contaminants_file} not found")
        sys.exit(1)
    
    if not materials_file.exists():
        print(f"❌ Error: {materials_file} not found")
        sys.exit(1)
    
    print('=' * 80)
    print('🔄 MATERIAL CONTAMINANTS SYNC (HYBRID APPROACH)')
    print('=' * 80)
    print()
    print('Architecture:')
    print('   SOURCE: Contaminants.yaml (edit this manually)')
    print('   CACHE:  Materials.yaml (auto-generated)')
    print()
    
    if args.dry_run:
        print('🔍 DRY RUN MODE - No changes will be saved')
        print()
    
    # Load data
    print('📂 Loading data files...')
    contaminants_data = read_yaml_file(contaminants_file)
    materials_data = read_yaml_file(materials_file)
    
    patterns_count = len(contaminants_data.get('contamination_patterns', {}))
    materials_count = len(materials_data.get('materials', {}))
    
    print(f'   ✅ Loaded {patterns_count} contamination patterns')
    print(f'   ✅ Loaded {materials_count} materials')
    print()
    
    # Build reverse index
    print('🔍 Building material → contaminants index...')
    contaminant_index = build_material_contaminant_index(contaminants_data)
    
    materials_with_data = len(contaminant_index)
    total_associations = sum(
        len(data['valid']) + len(data['prohibited']) 
        for data in contaminant_index.values()
    )
    
    print(f'   ✅ {materials_with_data} materials have contamination data')
    print(f'   ✅ {total_associations} total associations')
    print()
    
    # Show filter if specific materials requested
    if args.materials:
        print(f'🎯 Updating specific materials: {", ".join(args.materials)}')
        print()
    
    # Populate materials
    print('📝 Populating materials...')
    print()
    
    updated_data, updated_count, skipped_count, added_count = populate_materials(
        materials_data,
        contaminant_index,
        specific_materials=args.materials,
        verbose=args.verbose
    )
    
    # Summary
    print()
    print('=' * 80)
    print('📊 SUMMARY')
    print('=' * 80)
    print()
    print(f'   Materials updated:       {updated_count}')
    print(f'   Materials skipped:       {skipped_count} (no contamination data)')
    print(f'   Total contaminants added: {added_count}')
    print()
    
    # Show examples
    if updated_count > 0 and not args.verbose:
        print('📋 EXAMPLES:')
        print()
        
        example_count = 0
        for material_name, material_data in updated_data.get('materials', {}).items():
            contaminants = material_data.get('common_contaminants', [])
            if contaminants and example_count < 5:
                print(f'   {material_name}:')
                print(f'      → {len(contaminants)} contaminants: {", ".join(contaminants[:3])}' +
                      (f' (+{len(contaminants)-3} more)' if len(contaminants) > 3 else ''))
                example_count += 1
        print()
    
    # Save or preview
    if args.dry_run:
        print('🔍 DRY RUN COMPLETE - No changes saved')
        print()
        print('   To apply changes, run without --dry-run flag:')
        print('   python3 scripts/sync/populate_material_contaminants.py')
    else:
        print('💾 Saving Materials.yaml...')
        # Create backup if requested
        if not args.no_backup and materials_file.exists():
            backup_path = materials_file.with_suffix('.yaml.bak')
            if not backup_path.exists():
                print(f"📦 Creating backup: {backup_path.name}")
                import shutil
                shutil.copy2(materials_file, backup_path)
        write_yaml_file(materials_file, updated_data, sort_keys=False)
        print('   ✅ Saved successfully')
        print()
        print('✨ SYNC COMPLETE')
        print()
        print('   Materials.yaml now has cached common_contaminants field')
        print('   Lookups in both directions are now O(1)')
    
    print()


if __name__ == '__main__':
    main()
