"""
API MODULE DIRECTIVES FOR AI ASSISTANTS:
1. MINIMAL IMPLEMENTATION: This provider should be lightweight
2. NO EXTERNAL DEPENDENCIES: Don't require any external libraries
3. HELPFUL ERRORS: Provide useful diagnostic information
"""

import logging
from typing import Dict, Any, Optional, List
from api.providers.base import BaseProvider

logger = logging.getLogger(__name__)

class FallbackProvider(BaseProvider):
    """Fallback provider that generates placeholder content."""
    
    def __init__(self, context: Optional[Dict[str, Any]] = None):
        """Initialize the fallback provider.
        
        Args:
            context: Context for the provider
        """
        super().__init__(context)
        logger.warning("Using fallback provider - limited functionality available")
        
    def generate(self, prompt: str, options: Optional[Dict[str, Any]] = None) -> str:
        """Generate placeholder text.
        
        Args:
            prompt: Prompt to use for generation (ignored)
            options: Additional options for generation (ignored)
            
        Returns:
            Placeholder text explaining the fallback situation
        """
        logger.info("Fallback provider generating placeholder content")
        options = options or {}
        
        # Extract relevant information from the context
        subject = self.context.get("subject", "Unknown")
        article_type = self.context.get("article_type", "Unknown")
        
        # Generate placeholder content
        return f"""<!-- FALLBACK CONTENT -->
# {subject} ({article_type})

This content was generated by the fallback provider because no AI providers were available.

## Requested Generation
The system attempted to generate content with the following parameters:
- Subject: {subject}
- Article Type: {article_type}
- Provider: {options.get("provider", "Not specified")}
- Model: {options.get("model", self.get_default_model())}

## Troubleshooting Steps
1. Check if API keys are properly configured
2. Verify network connectivity
3. Ensure requested provider/model is available
4. Check the logs for specific error messages

<!-- END FALLBACK CONTENT -->
"""
        
    def get_default_model(self) -> str:
        """Get default model name.
        
        Returns:
            Default model name
        """
        return "fallback-model"
        
    def check_availability(self) -> bool:
        """Check if provider is available.
        
        Returns:
            Always True for fallback provider
        """
        return True
        
    def get_available_models(self) -> List[str]:
        """Get list of available models.
        
        Returns:
            List containing only the fallback model
        """
        return [self.get_default_model()]
        
    def validate_options(self, options: Dict[str, Any]) -> None:
        """Validate options for this provider.
        
        Args:
            options: Options to validate
        """
        # All options are valid for fallback provider
        pass